# Generated by Django 3.2.7 on 2021-09-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exldata',
            name='github',
            field=models.URLField(default=''),
        ),
    ]
